<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\Survivors\**" />
    <Compile Remove="SkillStates\Regigigas\Misc\**" />
    <EmbeddedResource Remove="Modules\Survivors\**" />
    <EmbeddedResource Remove="SkillStates\Regigigas\Misc\**" />
    <None Remove="Modules\Survivors\**" />
    <None Remove="SkillStates\Regigigas\Misc\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="regigigas" />
    <None Remove="regigigas2" />
    <None Remove="RegigigasBank.bnk" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BepInEx.Core" Version="5.4.19" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
		<PackageReference Include="UnityEngine.Modules" Version="2019.4.26" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.11.19">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="R2API" Version="4.3.5" />
	</ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="regigigas" />
    <EmbeddedResource Include="regigigas2" />
    <EmbeddedResource Include="RegigigasBank.bnk" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Decalicious">
      <HintPath>libs\Decalicious.dll</HintPath>
    </Reference>
    <Reference Include="RiskOfOptions">
      <HintPath>libs\RiskOfOptions.dll</HintPath>
    </Reference>
    <Reference Include="Risky_Artifacts">
      <HintPath>libs\Risky_Artifacts.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>..\..\Hunk\HunkProject\libs\Unity.Postprocessing.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Modules\Components\SlowStartController.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="call &quot;$(ProjectDir)weave.bat&quot;&#xD;&#xA;if &quot;$(Username)&quot; == &quot;Erikbir&quot; copy /Y &quot;$(TargetPath)&quot; &quot;$(ProjectDir)\..\ReleaseStuff&quot;&#xD;&#xA;&#xD;&#xA;if &quot;$(Username)&quot; == &quot;Erikbir&quot; copy &quot;$(TargetPath)&quot; &quot;E:\r2Profiles\Blinx Returns\BepInEx\plugins\TheTimesweeper-Regigigas&quot;&#xD;&#xA;if &quot;$(Username)&quot; == &quot;Erikbir&quot; copy &quot;$(TargetPath)&quot; &quot;E:\r2Profiles\uh help\BepInEx\plugins\TheTimesweeper-Regigigas&quot;&#xD;&#xA;if &quot;$(Username)&quot; == &quot;Erikbir&quot; mkdir &quot;C:\EnforcerBuild\plugins\TheTimesweeper-Regigigas&quot;&#xD;&#xA;if &quot;$(Username)&quot; == &quot;Erikbir&quot; copy /Y &quot;$(TargetPath)&quot; &quot;C:\EnforcerBuild\plugins\TheTimesweeper-Regigigas&quot;" />
  </Target>
  
</Project>
